BEGIN;

CREATE TYPE ACCOUNT_STATUS AS ENUM ('ACTIVE', 'INACTIVE', 'PENDING', 'SUSPENDED');
CREATE TYPE GENDER AS ENUM ('MALE', 'FEMALE', 'OTHERS');

CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  password VARCHAR(250) NOT NULL,
  email VARCHAR(300) UNIQUE NOT NULL,
  first_name VARCHAR(100),
  last_name VARCHAR(100),
  account_status ACCOUNT_STATUS DEFAULT 'PENDING',
  avatar VARCHAR(250),
  birth_date DATE,
  gender GENDER NULL,
  address VARCHAR(1000),
  user_timezone VARCHAR(100),
  description TEXT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMPTZ NULL
);

COMMIT;
